# DO NOT MODIFY: This file was generated by scripts/generate_arax_tests
from dataclasses import replace

import pytest
from translator_tom import Response

import xcrg
from tests.utilities import (
    XCRG_Answer,
    assert_answer,
    find_chemicals_affecting_gene,
)

TEST_NAME = "arax_test_decreased_ace"

@pytest.fixture(scope = "module")
def response(config: xcrg.XCRGConfig) -> Response:
    config = replace(config, debug_run_name = TEST_NAME)
    return find_chemicals_affecting_gene(config, "decreased", "NCBIGene:1636") # ACE

@pytest.mark.xdist_group(name = TEST_NAME)
@pytest.mark.parametrize(
    "answer",
    [
        XCRG_Answer("CHEBI:8713", "Quinapril", "top_answer"),
        XCRG_Answer("UNII:R43D2573WO", "Fosinopril", "top_answer", fails_on_arax = True),
        XCRG_Answer("CHEBI:6960", "Moexipril", "top_answer"),
        XCRG_Answer("CHEBI:3380", "Captopril", "top_answer"),
        XCRG_Answer("CHEBI:3011", "Benazapril", "top_answer"),
        XCRG_Answer("CHEBI:4784", "Enalapril", "top_answer"),
        XCRG_Answer("CHEBI:8774", "Ramipril", "top_answer"),
        XCRG_Answer("CHEBI:8024", "Perindopril", "top_answer"),
        XCRG_Answer("CHEBI:43755", "Lisinopril", "top_answer"),
        XCRG_Answer("CHEBI:9649", "Trandolapril", "top_answer"),
    ]
)
def test_decreased_activity_or_abundance_of_ace(response: Response, answer: XCRG_Answer):
    assert_answer(response, answer)
