# DO NOT MODIFY: This file was generated by scripts/generate_arax_tests
from dataclasses import replace

import pytest
from translator_tom import Response

import xcrg
from tests.utilities import (
    XCRG_Answer,
    assert_answer,
    find_chemicals_affecting_gene,
)

TEST_NAME = "arax_test_decreased_cyp2d6"

@pytest.fixture(scope = "module")
def response(config: xcrg.XCRGConfig) -> Response:
    config = replace(config, debug_run_name = TEST_NAME)
    return find_chemicals_affecting_gene(config, "decreased", "NCBIGene:1565") # CYP2D6

@pytest.mark.xdist_group(name = TEST_NAME)
@pytest.mark.parametrize(
    "answer",
    [
        XCRG_Answer("CHEBI:4636", "Diphenhydramine", "top_answer", fails_on_arax = True),
        XCRG_Answer("CHEBI:2663", "Amiodarone", "top_answer", fails_on_arax = True),
        XCRG_Answer("CHEBI:48390", "Cinacalcet", "top_answer", fails_on_arax = True),
        XCRG_Answer("CHEBI:7936", "Paroxetine", "top_answer"),
        XCRG_Answer("CHEBI:28593", "Quinidine", "top_answer"),
        XCRG_Answer("CHEBI:5118", "Fluoxetine", "top_answer"),
        XCRG_Answer("CHEBI:36795", "Duloxetine", "top_answer"),
        XCRG_Answer("CHEBI:3219", "Bupropion", "top_answer"),
        XCRG_Answer("CHEBI:9566", "Thioridazine", "acceptable"),
        XCRG_Answer("CHEBI:8069", "Phenobarbital", "never_show", fails_on_arax = True),
        XCRG_Answer("CHEBI:3387", "Carbamazepine", "never_show", fails_on_arax = True),
        XCRG_Answer("CHEBI:8107", "Phenytoin", "never_show"),
        XCRG_Answer("PUBCHEM.COMPOUND:3663", "St. John's Wort (Hypericum perforatum)", "never_show"),
        XCRG_Answer("CHEBI:28077", "Rifampicin", "never_show"),
    ]
)
def test_decreased_activity_or_abundance_of_cyp2d6(response: Response, answer: XCRG_Answer):
    assert_answer(response, answer)
