# DO NOT MODIFY: This file was generated by scripts/generate_arax_tests
from dataclasses import replace

import pytest
from translator_tom import Response

import xcrg
from tests.utilities import (
    XCRG_Answer,
    assert_answer,
    find_chemicals_affecting_gene,
)

TEST_NAME = f"arax_test_87bab1d7-8cf7-485c-b4c0-b6adda7f62b7"

@pytest.fixture(scope = "module")
def response(config: xcrg.XCRGConfig) -> Response:
    config = replace(config, debug_run_name = TEST_NAME)
    return find_chemicals_affecting_gene(config, "increased", "NCBIGene:154") # ADRB2

@pytest.mark.xdist_group(name = TEST_NAME)
@pytest.mark.parametrize(
    "answer",
    [
        XCRG_Answer("CHEBI:64064", "top_answer"), # salmeterol
        XCRG_Answer("CHEBI:5147", "top_answer"), # formoterol
        XCRG_Answer("CHEBI:9449", "top_answer"), # terbutaline
        XCRG_Answer("CHEBI:2549", "top_answer"), # Albuterol
        XCRG_Answer("CHEBI:8499", "never_show", fails_on_arax = True), # Propranolol
    ]
)
def test_increased_activity_or_abundance_of_adrb2(response: Response, answer: XCRG_Answer):
    assert_answer(response, answer)
