# DO NOT MODIFY: This file was generated by scripts/generate_arax_tests
from dataclasses import replace

import pytest
from translator_tom import Response

import xcrg
from tests.utilities import (
    XCRG_Answer,
    assert_answer,
    find_genes_affected_by_chemical,
)

TEST_NAME = "arax_test_decreased_lepirudin"

@pytest.fixture(scope = "module")
def response(config: xcrg.XCRGConfig) -> Response:
    config = replace(config, debug_run_name = TEST_NAME)
    return find_genes_affected_by_chemical(config, "decreased", "CHEBI:142437") # Lepirudin

@pytest.mark.xdist_group(name = TEST_NAME)
@pytest.mark.parametrize(
    "answer",
    [
        # BUG: https://github.com/NCATSTranslator/Tests/issues/83
        # Both of the top answers suffer from this issue
        XCRG_Answer("NCBIGene:2147", "F2", "top_answer"),
        # TODO: Are these entities the same or different?
        # XCRG_Test("UMLS:C0040018", "top_answer", expected_to_fail = True), # Thrombin
        XCRG_Answer("CHEMBL.COMPOUND:CHEMBL2108110", "Thrombin", "top_answer", fails_on_arax = True),
        XCRG_Answer("NCBIGene:2670", "GFAP", "never_show"),
        XCRG_Answer("NCBIGene:6774", "STAT3", "never_show"),
        XCRG_Answer("NCBIGene:7108", "TM7SF2", "never_show"),
        XCRG_Answer("NCBITaxon:1603998", "JACK2", "never_show"),
        XCRG_Answer("NCBIGene:283", "ANG", "never_show"),
        XCRG_Answer("NCBIGene:80150", "ASRGL1", "never_show"),
        XCRG_Answer("NCBIGene:5604", "MAP2K1", "never_show"),
        XCRG_Answer("NCBIGene:10891", "PPARGC1A", "never_show"),
        XCRG_Answer("NCBIGene:97828105", "RHO", "never_show"),
        XCRG_Answer("NCBIGene:998", "CDC42", "never_show"),
        XCRG_Answer("NCBIGene:133522", "PPARGC1B", "never_show"),
        XCRG_Answer("NCBIGene:27295", "PDLIM3", "never_show"),
        XCRG_Answer("NCBIGene:7311", "UBA52", "never_show"),
        XCRG_Answer("NCBIGene:920", "CD4", "never_show"),
        XCRG_Answer("NCBIGene:7442", "TRPV1", "never_show"),
        XCRG_Answer("NCBITaxon:1352719", "PCAM1", "never_show"),
        XCRG_Answer("NCBIGene:5553", "PRG2", "never_show"),
        XCRG_Answer("NCBIGene:6590", "SLPI", "never_show"),
        XCRG_Answer("NCBIGene:1435", "CSF1", "never_show"),
        XCRG_Answer("NCBIGene:808252", "COX2", "never_show"),
        XCRG_Answer("NCBIGene:29126", "CD274", "never_show"),
        XCRG_Answer("NCBIGene:595", "CCND1", "never_show"),
        XCRG_Answer("NCBIGene:2048", "EPHB2", "never_show"),
        XCRG_Answer("NCBIGene:9402", "GRAP2", "never_show"),
        XCRG_Answer("NCBIGene:3576", "CXCL8", "never_show"),
        XCRG_Answer("NCBIGene:3567", "IL5", "never_show"),
        XCRG_Answer("NCBIGene:1958", "EGR1", "never_show"),
        XCRG_Answer("NCBIGene:468", "ATF4", "never_show"),
        XCRG_Answer("NCBIGene:4843", "NOS2", "never_show"),
        XCRG_Answer("NCBIGene:4214", "MAP3K1", "never_show"),
        XCRG_Answer("NCBIGene:8408", "ULK1", "never_show"),
        XCRG_Answer("NCBIGene:284", "ANGPT1", "never_show"),
        XCRG_Answer("NCBIGene:894", "CCND2", "never_show"),
        XCRG_Answer("NCBIGene:3574", "IL7", "never_show"),
        XCRG_Answer("NCBIGene:7020", "TFAP2A", "never_show"),
        XCRG_Answer("NCBIGene:891", "CCNB1", "never_show"),
        XCRG_Answer("NCBIGene:1901", "S1PR1", "never_show"),
        XCRG_Answer("NCBIGene:6772", "STAT1", "never_show"),
        XCRG_Answer("NCBIGene:348", "APOE", "never_show"),
        XCRG_Answer("NCBIGene:100513441", "ATF2", "never_show"),
        XCRG_Answer("NCBIGene:3976", "LIF", "never_show"),
        XCRG_Answer("NCBIGene:5534", "PPP3R1", "never_show"),
        XCRG_Answer("NCBIGene:6233", "RPS27A", "never_show"),
        XCRG_Answer("NCBIGene:2919", "CXCL1", "never_show"),
        XCRG_Answer("NCBIGene:5328", "PLAU", "never_show"),
        XCRG_Answer("NCBIGene:4170", "MCL1", "never_show"),
        XCRG_Answer("NCBIGene:285", "ANGPT2", "never_show"),
        XCRG_Answer("NCBIGene:10133", "OPTN", "never_show"),
        XCRG_Answer("NCBIGene:10850", "CCL27", "never_show"),
        XCRG_Answer("NCBIGene:2099", "ESR1", "never_show"),
        XCRG_Answer("NCBIGene:2475", "MTOR", "never_show"),
        XCRG_Answer("NCBIGene:100506658", "OCLN", "never_show"),
        XCRG_Answer("NCBIGene:3725", "JUN", "never_show"),
        XCRG_Answer("NCBIGene:1385", "CREB1", "never_show"),
        XCRG_Answer("NCBIGene:857", "CAV1", "never_show"),
        XCRG_Answer("NCBIGene:4803", "NGF", "never_show"),
        XCRG_Answer("NCBIGene:14268", "FN1", "never_show"),
        XCRG_Answer("NCBIGene:339345", "NANOS2", "never_show"),
        XCRG_Answer("NCBIGene:29072", "SETD2", "never_show"),
        XCRG_Answer("NCBIGene:1437", "CSF2", "never_show"),
        XCRG_Answer("NCBIGene:22926", "ATF6", "never_show"),
        XCRG_Answer("NCBIGene:1843", "DUSP1", "never_show"),
        XCRG_Answer("NCBIGene:5594", "MAPK1", "never_show"),
        XCRG_Answer("NCBIGene:3480", "IGF1R", "never_show"),
        XCRG_Answer("NCBIGene:3596", "IL13", "never_show"),
        XCRG_Answer("NCBIGene:5345", "SERPINF2", "never_show"),
        XCRG_Answer("NCBIGene:24547", "MBP", "never_show"),
        XCRG_Answer("NCBIGene:10875", "FGL2", "never_show"),
        XCRG_Answer("NCBIGene:55226", "NAT10", "never_show"),
        XCRG_Answer("NCBIGene:2167", "FABP4", "never_show"),
        XCRG_Answer("NCBIGene:947", "CD34", "never_show"),
        XCRG_Answer("NCBIGene:100154503", "SRC", "never_show"),
        XCRG_Answer("NCBIGene:655", "BMP7", "never_show"),
        XCRG_Answer("NCBIGene:361", "AQP4", "never_show"),
        XCRG_Answer("NCBIGene:27352", "SGSM3", "never_show"),
        XCRG_Answer("NCBIGene:7316", "UBC", "never_show"),
        XCRG_Answer("NCBIGene:8720", "MBTPS1", "never_show"),
        XCRG_Answer("NCBIGene:860", "RUNX2", "never_show"),
        XCRG_Answer("NCBIGene:10928", "RALBP1", "never_show"),
        XCRG_Answer("NCBIGene:5743", "PTGS2", "never_show"),
        XCRG_Answer("NCBIGene:7314", "UBB", "never_show"),
        XCRG_Answer("NCBIGene:3661", "IRF3", "never_show"),
        XCRG_Answer("NCBIGene:6382", "SDC1", "never_show"),
        XCRG_Answer("NCBIGene:494460", "CXCL12", "never_show"),
        XCRG_Answer("NCBIGene:896", "CCND3", "never_show"),
        XCRG_Answer("NCBIGene:1956", "EGFR", "never_show"),
        XCRG_Answer("NCBIGene:23409", "SIRT4", "never_show"),
        XCRG_Answer("NCBIGene:6646", "SOAT1", "never_show"),
        XCRG_Answer("NCBIGene:423915", "ATRNL1", "never_show"),
    ]
)
def test_decreased_activity_or_abundance_of_lepirudin(response: Response, answer: XCRG_Answer):
    assert_answer(response, answer)
