# DO NOT MODIFY: This file was generated by scripts/generate_arax_tests
from dataclasses import replace

import pytest
from translator_tom import Response

import xcrg
from tests.utilities import (
    XCRG_Answer,
    assert_answer,
    find_genes_affected_by_chemical,
)

TEST_NAME = "arax_test_decreased_bivalirudin"

@pytest.fixture(scope = "module")
def response(config: xcrg.XCRGConfig) -> Response:
    config = replace(config, debug_run_name = TEST_NAME)
    return find_genes_affected_by_chemical(config, "decreased", "CHEBI:59173") # Bivalirudin

@pytest.mark.xdist_group(name = TEST_NAME)
@pytest.mark.parametrize(
    "answer",
    [
        XCRG_Answer("UMLS:C0040018", "Thrombin", "top_answer", fails_on_arax = True),
        XCRG_Answer("NCBIGene:4353", "MPO", "top_answer"),
        XCRG_Answer("NCBIGene:2147", "F2", "top_answer"),
        # BUG: https://github.com/NCATSTranslator/Tests/issues/83
        XCRG_Answer("CHEMBL.TARGET:CHEMBL204", "UNIPROTKB#P00734", "top_answer", fails_on_arax = True),
    ]
)
def test_decreased_activity_or_abundance_of_bivalirudin(response: Response, answer: XCRG_Answer):
    assert_answer(response, answer)
