# DO NOT MODIFY: This file was generated by scripts/generate_arax_tests
from dataclasses import replace

import xcrg
from tests.utilities import XCRG_Answer, assert_answer
from xcrg.dev import (
    Query_Args,
    find_chemicals_affecting_gene,
    find_genes_affected_by_chemical,
)
from xcrg.models import Direction


def test_ivacaftor_increased_activity_or_abundance_of_cftr(config: xcrg.XCRGConfig):
    config = replace(config, debug_run_name = "arax_test_increased_cftr")
    args = Query_Args(Direction.INCREASED, "NCBIGene:1080")  # CFTR
    response = find_chemicals_affecting_gene(config, args)
    assert_answer(response, XCRG_Answer("CHEBI:66901", "Ivacaftor", "acceptable"))

def test_adra2a_increased_activity_or_abundance_of_guafacine(config: xcrg.XCRGConfig):
    config = replace(config, debug_run_name = "arax_test_increased_guafacine")
    args = Query_Args(Direction.INCREASED, "CHEBI:5558")  # Guafacine
    response = find_genes_affected_by_chemical(config, args)
    assert_answer(response, XCRG_Answer("NCBIGene:150", "ADRA2A", "acceptable"))

def test_bcl2_decreased_activity_or_abundance_of_docetaxel(config: xcrg.XCRGConfig):
    config = replace(config, debug_run_name = "arax_test_decreased_docetaxel")
    args = Query_Args(Direction.DECREASED, "CHEBI:4672")  # Docetaxel
    response = find_genes_affected_by_chemical(config, args)
    assert_answer(response, XCRG_Answer("NCBIGene:596", "BCL2", "acceptable"))

def test_guafacine_increased_activity_or_abundance_of_dlg4(config: xcrg.XCRGConfig):
    config = replace(config, debug_run_name = "arax_test_increased_dlg4")
    args = Query_Args(Direction.INCREASED, "NCBIGene:1742")  # DLG4
    response = find_chemicals_affecting_gene(config, args)
    assert_answer(response, XCRG_Answer("CHEBI:5558", "Guafacine", "acceptable"))

def test_ng_nitroarginine_methyl_ester_increased_activity_or_abundance_of_acetylcholine(config: xcrg.XCRGConfig):
    config = replace(config, debug_run_name = "arax_test_increased_acetylcholine")
    args = Query_Args(Direction.INCREASED, "CHEBI:15355")  # Acetylcholine
    response = find_genes_affected_by_chemical(config, args)
    assert_answer(response, XCRG_Answer("UMLS:C0083536", "NG-Nitroarginine Methyl Ester", "never_show"))

def test_cancer_decreased_activity_or_abundance_of_myc(config: xcrg.XCRGConfig):
    config = replace(config, debug_run_name = "arax_test_decreased_myc")
    args = Query_Args(Direction.DECREASED, "NCBIGene:4609")  # MYC
    response = find_genes_affected_by_chemical(config, args)
    assert_answer(response, XCRG_Answer("MONDO:0004992", "cancer", "never_show"))

def test_ppara_increased_activity_or_abundance_of_clofibric_acid(config: xcrg.XCRGConfig):
    config = replace(config, debug_run_name = "arax_test_increased_clofibric_acid")
    args = Query_Args(Direction.INCREASED, "CHEBI:34648")  # clofibric acid
    response = find_genes_affected_by_chemical(config, args)
    assert_answer(response, XCRG_Answer("NCBIGene:5465", "PPARA", "top_answer"))

def test_dabrafenib_decreased_activity_or_abundance_of_braf(config: xcrg.XCRGConfig):
    config = replace(config, debug_run_name = "arax_test_decreased_braf")
    args = Query_Args(Direction.DECREASED, "NCBIGene:673")  # BRAF
    response = find_chemicals_affecting_gene(config, args)
    assert_answer(response, XCRG_Answer("CHEBI:75045", "Dabrafenib", "acceptable"))

# TODO: This fails on ARAX because the output_id "NCBI:2629" is incorrect?
def test_gba1_decreased_activity_or_abundance_of_eliglustat(config: xcrg.XCRGConfig):
    config = replace(config, debug_run_name = "arax_test_decreased_eliglustat")
    args = Query_Args(Direction.DECREASED, "CHEBI:82752")  # Eliglustat
    response = find_genes_affected_by_chemical(config, args)
    assert_answer(response, XCRG_Answer("NCBIGene:2629", "GBA1", "acceptable", fails_on_arax = True))

def test_canagliflozin_decreased_activity_or_abundance_of_slc5a2(config: xcrg.XCRGConfig):
    config = replace(config, debug_run_name = "arax_test_decreased_slc5a2")
    args = Query_Args(Direction.DECREASED, "NCBIGene:6524")  # SLC5A2
    response = find_chemicals_affecting_gene(config, args)
    assert_answer(response, XCRG_Answer("CHEBI:73274", "Canagliflozin", "top_answer"))

def test_naphthalene_decreased_activity_or_abundance_of_bpifa1(config: xcrg.XCRGConfig):
    config = replace(config, debug_run_name = "arax_test_decreased_bpifa1")
    args = Query_Args(Direction.DECREASED, "NCBIGene:51297")  # BPIFA1
    response = find_chemicals_affecting_gene(config, args)
    assert_answer(response, XCRG_Answer("CHEBI:16482", "Naphthalene", "acceptable"))

def test_acarbose_decreased_activity_or_abundance_of_mgam(config: xcrg.XCRGConfig):
    config = replace(config, debug_run_name = "arax_test_decreased_mgam")
    args = Query_Args(Direction.DECREASED, "NCBIGene:8972")  # MGAM
    response = find_chemicals_affecting_gene(config, args)
    assert_answer(response, XCRG_Answer("CHEBI:2376", "Acarbose", "top_answer", fails_on_arax = True))

def test_warfarin_decreased_activity_or_abundance_of_vkorc1(config: xcrg.XCRGConfig):
    config = replace(config, debug_run_name = "arax_test_decreased_vkorc1")
    args = Query_Args(Direction.DECREASED, "NCBIGene:79001")  # VKORC1
    response = find_chemicals_affecting_gene(config, args)
    assert_answer(response, XCRG_Answer("CHEBI:10033", "Warfarin", "top_answer"))

def test_cyp3a4_decreased_activity_or_abundance_of_nirmatrelvir(config: xcrg.XCRGConfig):
    config = replace(config, debug_run_name = "arax_test_decreased_nirmatrelvir")
    args = Query_Args(Direction.DECREASED, "CHEBI:170007")  # Nirmatrelvir
    response = find_genes_affected_by_chemical(config, args)
    assert_answer(response, XCRG_Answer("NCBIGene:1576", "CYP3A4", "acceptable", fails_on_arax = True))

def test_ppara_increased_activity_or_abundance_of_permethrin(config: xcrg.XCRGConfig):
    config = replace(config, debug_run_name = "arax_test_increased_permethrin")
    args = Query_Args(Direction.INCREASED, "CHEBI:34911")  # Permethrin
    response = find_genes_affected_by_chemical(config, args)
    assert_answer(response, XCRG_Answer("NCBIGene:5465", "PPARA", "top_answer", fails_on_arax = True))

def test_sildenafil_decreased_activity_or_abundance_of_pde5a(config: xcrg.XCRGConfig):
    config = replace(config, debug_run_name = "arax_test_decreased_pde5a")
    args = Query_Args(Direction.DECREASED, "NCBIGene:8654")  # PDE5A
    response = find_chemicals_affecting_gene(config, args)
    assert_answer(response, XCRG_Answer("CHEBI:9139", "Sildenafil", "top_answer"))

def test_mrtx_1133_decreased_activity_or_abundance_of_kras(config: xcrg.XCRGConfig):
    config = replace(config, debug_run_name = "arax_test_decreased_kras")
    args = Query_Args(Direction.DECREASED, "NCBIGene:3845")  # KRAS
    response = find_chemicals_affecting_gene(config, args)
    assert_answer(response, XCRG_Answer("PUBCHEM.COMPOUND:156124857", "MRTX-1133", "top_answer", fails_on_arax = True))
