# DO NOT MODIFY: This file was generated by scripts/generate_arax_tests
from dataclasses import replace

import pytest
from translator_tom import Response

import xcrg
from tests.utilities import (
    XCRG_Answer,
    assert_answer,
    find_genes_affected_by_chemical,
)

TEST_NAME = f"arax_test_3289146b-7275-4da8-959f-cff3160f46f0"

@pytest.fixture(scope = "module")
def response(config: xcrg.XCRGConfig) -> Response:
    config = replace(config, debug_run_name = TEST_NAME)
    return find_genes_affected_by_chemical(config, "decreased", "CHEBI:27744") # Glyphosate

@pytest.mark.xdist_group(name = TEST_NAME)
@pytest.mark.parametrize(
    "answer",
    [
        XCRG_Answer("NCBIGene:10381", "acceptable"), # TUBB3
        XCRG_Answer("NCBIGene:2596", "acceptable", fails_on_arax = True), # GAP43
    ]
)
def test_decreased_activity_or_abundance_of_glyphosate(response: Response, answer: XCRG_Answer):
    assert_answer(response, answer)
