# DO NOT MODIFY: This file was generated by scripts/generate_arax_tests
from dataclasses import replace

import pytest
from translator_tom import Response

import xcrg
from tests.utilities import (
    XCRG_Answer,
    assert_answer,
    find_chemicals_affecting_gene,
)

TEST_NAME = "arax_test_decreased_smarce1"

@pytest.fixture(scope = "module")
def response(config: xcrg.XCRGConfig) -> Response:
    config = replace(config, debug_run_name = TEST_NAME)
    return find_chemicals_affecting_gene(config, "decreased", "NCBIGene:6605") # SMARCE1

@pytest.mark.xdist_group(name = TEST_NAME)
@pytest.mark.parametrize(
    "answer",
    [
        XCRG_Answer("CHEBI:75998", "trametinib", "top_answer", fails_on_arax = True),
        XCRG_Answer("CHEBI:72564", "temozolomide", "top_answer", fails_on_arax = True),
        XCRG_Answer("UNII:DPT0O3T46P", "pembrolizumab", "top_answer", fails_on_arax = True),
        XCRG_Answer("CHEBI:39867", "valproic acid", "top_answer", fails_on_arax = True),
        XCRG_Answer("CHEBI:90943", "osimertinib", "acceptable", fails_on_arax = True),
        XCRG_Answer("CHEBI:114785", "erlotinib", "acceptable", fails_on_arax = True),
        XCRG_Answer("CHEBI:61390", "afatinib", "acceptable", fails_on_arax = True),
        XCRG_Answer("UMLS:C4085970", "amivantamab-vmjw", "acceptable", fails_on_arax = True),
        XCRG_Answer("HGNC.FAMILY:3410", "histone-lysine methyltransferases", "acceptable", fails_on_arax = True),
        XCRG_Answer("CHEBI:49668", "gefitinib", "acceptable", fails_on_arax = True),
        XCRG_Answer("CHEBI:132268", "dacomitinib", "acceptable", fails_on_arax = True),
        XCRG_Answer("PUBCHEM.COMPOUND:54671203", "doxycycline", "bad_but_forgivable", fails_on_arax = True),
    ]
)
def test_decreased_activity_or_abundance_of_smarce1(response: Response, answer: XCRG_Answer):
    assert_answer(response, answer)
