# DO NOT MODIFY: This file was generated by scripts/generate_arax_tests
from dataclasses import replace

import pytest
from translator_tom import Response

import xcrg
from tests.utilities import (
    XCRG_Answer,
    assert_answer,
    find_genes_affected_by_chemical,
)

TEST_NAME = "arax_test_decreased_mifepristone"

@pytest.fixture(scope = "module")
def response(config: xcrg.XCRGConfig) -> Response:
    config = replace(config, debug_run_name = TEST_NAME)
    return find_genes_affected_by_chemical(config, "decreased", "CHEBI:50692") # Mifepristone

@pytest.mark.xdist_group(name = TEST_NAME)
@pytest.mark.parametrize(
    "answer",
    [
        XCRG_Answer("NCBIGene:355", "FAS", "acceptable", fails_on_arax = True),
        XCRG_Answer("NCBIGene:356", "FASL", "acceptable", fails_on_arax = True),
        XCRG_Answer("NCBIGene:93659", "HCG", "acceptable", fails_on_arax = True),
    ]
)
def test_decreased_activity_or_abundance_of_mifepristone(response: Response, answer: XCRG_Answer):
    assert_answer(response, answer)
