# DO NOT MODIFY: This file was generated by scripts/generate_arax_tests
from dataclasses import replace

import pytest
from translator_tom import Response

import xcrg
from tests.utilities import (
    XCRG_Answer,
    assert_answer,
    find_chemicals_affecting_gene,
)

TEST_NAME = f"arax_test_b7e9e513-cde3-45ed-b366-38ea9da851b9"

@pytest.fixture(scope = "module")
def response(config: xcrg.XCRGConfig) -> Response:
    config = replace(config, debug_run_name = TEST_NAME)
    return find_chemicals_affecting_gene(config, "decreased", "NCBIGene:675") # BRCA2

@pytest.mark.xdist_group(name = TEST_NAME)
@pytest.mark.parametrize(
    "answer",
    [
        XCRG_Answer("UNII:9X5A2QIA7C", "acceptable", fails_on_arax = True), # PARP inhibitor 2X-121
        XCRG_Answer("CHEBI:16731", "bad_but_forgivable"), # Cinnamaldehyde
        XCRG_Answer("CHEBI:16842", "bad_but_forgivable", fails_on_arax = True), # Formaldehyde
        XCRG_Answer("PUBCHEM.COMPOUND:14423521", "bad_but_forgivable"), # Ursolic aldehyde
        XCRG_Answer("CHEBI:31355", "acceptable", fails_on_arax = True), # Carboplatin
        XCRG_Answer("CHEBI:176844", "acceptable"), # niraparib
        XCRG_Answer("CHEBI:83766", "acceptable"), # olaparib
        XCRG_Answer("CHEBI:62880", "acceptable"), # veliparib
        XCRG_Answer("CHEBI:134689", "acceptable", fails_on_arax = True), # rucaparib
        XCRG_Answer("CHEBI:231344", "acceptable"), # talazoparib
        XCRG_Answer("CHEBI:27899", "acceptable"), # Cisplatin
        XCRG_Answer("CHEBI:167900", "acceptable", fails_on_arax = True), # PJ34
        XCRG_Answer("CHEBI:41774", "acceptable"), # Tamoxifen
    ]
)
def test_decreased_activity_or_abundance_of_brca2(response: Response, answer: XCRG_Answer):
    assert_answer(response, answer)
