# DO NOT MODIFY: This file was generated by scripts/generate_arax_tests
from dataclasses import replace

import pytest
from translator_tom import Response

import xcrg
from tests.utilities import (
    XCRG_Answer,
    assert_answer,
    find_genes_affected_by_chemical,
)

TEST_NAME = "arax_test_increased_potassium_ion"

# ARAX has a number of duplicated tests in this suite: ATP1A1, ATP1A2, ATP1A3, etc.
# Some of these are documented in GitHub tickets: https://github.com/NCATSTranslator/Tests/issues/46
@pytest.fixture(scope = "module")
def response(config: xcrg.XCRGConfig) -> Response:
    config = replace(config, debug_run_name = TEST_NAME)
    return find_genes_affected_by_chemical(config, "increased", "CHEBI:29103") # Potassium ion

@pytest.mark.xdist_group(name = TEST_NAME)
@pytest.mark.parametrize(
    "answer",
    [
        XCRG_Answer("NCBIGene:249", "ALPL", "never_show"),
        XCRG_Answer("NCBIGene:7108", "TM7SF2", "never_show"),
        XCRG_Answer("NCBIGene:26330", "GAPDHS", "never_show"),
        XCRG_Answer("NCBIGene:477", "ATP1A2", "never_show"),
        XCRG_Answer("NCBIGene:2641", "GCG", "never_show"),
        XCRG_Answer("NCBIGene:80150", "ASRGL1", "never_show"),
        XCRG_Answer("NCBIGene:6402", "SELL", "never_show"),
        XCRG_Answer("NCBIGene:57154", "SMURF1", "never_show"),
        XCRG_Answer("NCBIGene:56302", "TRPV5", "never_show"),
        XCRG_Answer("NCBIGene:7311", "UBA52", "never_show"),
        XCRG_Answer("NCBIGene:11035", "RIPK3", "never_show"),
        XCRG_Answer("NCBIGene:7130", "TNFAIP6", "never_show"),
        XCRG_Answer("NCBIGene:6401", "SELE", "never_show"),
        XCRG_Answer("NCBIGene:1435", "CSF1", "never_show"),
        XCRG_Answer("NCBIGene:100125288", "ZGLP1", "never_show"),
        XCRG_Answer("NCBIGene:939", "CD27", "never_show"),
        XCRG_Answer("NCBIGene:8743", "TNFSF10", "never_show"),
        XCRG_Answer("NCBIGene:7472", "WNT2", "never_show"),
        XCRG_Answer("NCBIGene:51497", "NELFCD", "never_show"),
        XCRG_Answer("NCBIGene:738", "VPS51", "never_show"),
        XCRG_Answer("NCBIGene:3576", "CXCL8", "never_show"),
        XCRG_Answer("NCBIGene:148327", "CREB3L4", "never_show"),
        XCRG_Answer("NCBIGene:100154195", "GIT2", "never_show"),
        XCRG_Answer("NCBIGene:7128", "TNFAIP3", "never_show"),
        XCRG_Answer("NCBIGene:823", "CAPN1", "never_show"),
        XCRG_Answer("NCBIGene:4843", "NOS2", "never_show"),
        XCRG_Answer("NCBIGene:55824", "PAG1", "never_show"),
        XCRG_Answer("NCBIGene:23118", "TAB2", "never_show"),
        XCRG_Answer("NCBIGene:3952", "LEP", "never_show"),
        XCRG_Answer("NCBIGene:8811", "GALR2", "never_show"),
        XCRG_Answer("NCBIGene:7132", "TNFRSF1A", "never_show"),
        XCRG_Answer("NCBIGene:476", "ATP1A1", "never_show"),
        XCRG_Answer("NCBIGene:6403", "SELP", "never_show"),
        XCRG_Answer("NCBIGene:54884", "RETSAT", "never_show"),
        XCRG_Answer("NCBIGene:5428", "POLG", "never_show"),
        XCRG_Answer("NCBIGene:2919", "CXCL1", "never_show"),
        XCRG_Answer("NCBIGene:480", "ATP1A4", "never_show"),
        XCRG_Answer("NCBIGene:51330", "TNFRSF12A", "never_show"),
        XCRG_Answer("NCBIGene:285", "ANGPT2", "never_show"),
        XCRG_Answer("NCBIGene:100524014", "TNFAIP8", "never_show"),
        XCRG_Answer("NCBIGene:22861", "NLRP1", "never_show"),
        XCRG_Answer("NCBIGene:22943", "DKK1", "never_show"),
        XCRG_Answer("NCBIGene:6776", "STAT5A", "never_show"),
        XCRG_Answer("NCBIGene:1585", "CYP11B2", "never_show"),
        XCRG_Answer("NCBIGene:495", "ATP4A", "never_show"),
        XCRG_Answer("NCBIGene:1437", "CSF2", "never_show"),
        XCRG_Answer("NCBIGene:9421", "HAND1", "never_show"),
        XCRG_Answer("NCBIGene:397491", "IGF1", "never_show"),
        XCRG_Answer("NCBIGene:113905823", "CADM1", "never_show"),
        XCRG_Answer("NCBIGene:10488", "CREB3", "never_show"),
        XCRG_Answer("NCBIGene:2308", "FOXO1", "never_show"),
        XCRG_Answer("NCBIGene:479", "ATP12A", "never_show"),
        XCRG_Answer("NCBIGene:811", "CALR", "never_show"),
        XCRG_Answer("NCBIGene:25157163", "SOD", "never_show"),
        XCRG_Answer("NCBIGene:10010", "TANK", "never_show"),
        XCRG_Answer("NCBIGene:397665", "PCBP2", "never_show"),
        XCRG_Answer("NCBIGene:27352", "SGSM3", "never_show"),
        XCRG_Answer("NCBIGene:355", "FAS", "never_show"),
        XCRG_Answer("NCBIGene:4313", "MMP2", "never_show"),
        XCRG_Answer("NCBIGene:57410", "SCYL1", "never_show"),
        XCRG_Answer("NCBIGene:4314", "MMP3", "never_show"),
        XCRG_Answer("NCBIGene:958", "CD40", "never_show"),
        XCRG_Answer("NCBIGene:3562", "IL3", "never_show"),
        XCRG_Answer("NCBIGene:9943", "OXSR1", "never_show"),
        XCRG_Answer("UMLS:C0058605", "AdenosineTriphosphatases", "never_show"),
        XCRG_Answer("NCBIGene:5806", "PTX3", "never_show"),
        XCRG_Answer("NCBIGene:100513111", "NR2C2", "never_show"),
        XCRG_Answer("NCBIGene:1153", "CIRBP", "never_show"),
        XCRG_Answer("NCBIGene:3383", "ICAM1", "never_show"),
        XCRG_Answer("NCBIGene:147138", "TMC8", "never_show"),
        XCRG_Answer("NCBIGene:200186", "CRTC2", "never_show", fails_on_arax = True),
        XCRG_Answer("NCBIGene:2597", "GAPDH", "never_show"),
        XCRG_Answer("NCBIGene:650", "BMP2", "never_show"),
        XCRG_Answer("NCBIGene:1956", "EGFR", "never_show"),
        XCRG_Answer("NCBIGene:478", "ATP1A3", "never_show"),
        XCRG_Answer("NCBIGene:7098", "TLR3", "never_show"),
        XCRG_Answer("NCBIGene:100135663", "MAP3K7", "never_show"),
        XCRG_Answer("NCBIGene:8717", "TRADD", "never_show"),
        XCRG_Answer("NCBIGene:6646", "SOAT1", "never_show"),
        XCRG_Answer("UMLS:C0001473", "Adenosine Triphosphatases", "never_show"),
    ]
)
def test_increased_activity_or_abundance_of_potassium_ion(response: Response, answer: XCRG_Answer):
    assert_answer(response, answer)
