# DO NOT MODIFY: This file was generated by scripts/generate_arax_tests
from dataclasses import replace

import pytest
from translator_tom import Response

import xcrg
from tests.utilities import (
    XCRG_Answer,
    assert_answer,
    find_chemicals_affecting_gene,
)

TEST_NAME = "arax_test_decreased_adrb2"

@pytest.fixture(scope = "module")
def response(config: xcrg.XCRGConfig) -> Response:
    config = replace(config, debug_run_name = TEST_NAME)
    return find_chemicals_affecting_gene(config, "decreased", "NCBIGene:154") # ADRB2

@pytest.mark.xdist_group(name = TEST_NAME)
@pytest.mark.parametrize(
    "answer",
    [
        XCRG_Answer("CHEBI:3441", "carvedilol", "top_answer"),
        XCRG_Answer("CHEBI:17579", "Beta-Blockers (Inhibitors)", "top_answer", fails_on_arax = True),
        XCRG_Answer("CHEBI:6904", "metoprolol", "top_answer"),
        XCRG_Answer("CHEBI:8499", "propranolol", "top_answer", fails_on_arax = True),
        XCRG_Answer("CHEBI:2904", "atenolol", "top_answer"),
        XCRG_Answer("CHEBI:91879", "ICI-118,551 (ZENIDOLOL?)", "top_answer", fails_on_arax = True),
        XCRG_Answer("UNII:0NM31M53PW", "Butaxamine", "acceptable", fails_on_arax = True),
    ]
)
def test_decreased_activity_or_abundance_of_adrb2(response: Response, answer: XCRG_Answer):
    assert_answer(response, answer)
