# DO NOT MODIFY: This file was generated by scripts/generate_arax_tests
from dataclasses import replace

import pytest
from translator_tom import Response

import xcrg
from tests.utilities import (
    XCRG_Answer,
    assert_answer,
    find_genes_affected_by_chemical,
)

TEST_NAME = "arax_test_090be321-0978-47fd-9d02-0e98670cfbb7"

@pytest.fixture(scope = "module")
def response(config: xcrg.XCRGConfig) -> Response:
    config = replace(config, debug_run_name = TEST_NAME)
    return find_genes_affected_by_chemical(config, "decreased", "CHEBI:74947") # Thalidomide

@pytest.mark.xdist_group(name = TEST_NAME)
@pytest.mark.parametrize(
    "answer",
    [
        XCRG_Answer("NCBIGene:5004", "acceptable", fails_on_arax = True), # ORM1
        XCRG_Answer("NCBIGene:57167", "acceptable"), # SALL4
        XCRG_Answer("NCBIGene:5005", "acceptable", fails_on_arax = True), # ORM2
    ]
)
def test_decreased_activity_or_abundance_of_thalidomide(response: Response, answer: XCRG_Answer):
    assert_answer(response, answer)
