# DO NOT MODIFY: This file was generated by scripts/generate_arax_tests
from dataclasses import replace

import pytest
from translator_tom import Response

import xcrg
from tests.utilities import (
    XCRG_Answer,
    assert_answer,
    find_chemicals_affecting_gene,
)

TEST_NAME = "arax_test_increased_adrb2"

@pytest.fixture(scope = "module")
def response(config: xcrg.XCRGConfig) -> Response:
    config = replace(config, debug_run_name = TEST_NAME)
    return find_chemicals_affecting_gene(config, "increased", "NCBIGene:154") # ADRB2

@pytest.mark.xdist_group(name = TEST_NAME)
@pytest.mark.parametrize(
    "answer",
    [
        XCRG_Answer("CHEBI:64064", "salmeterol", "top_answer"),
        XCRG_Answer("CHEBI:5147", "formoterol", "top_answer"),
        XCRG_Answer("CHEBI:9449", "terbutaline", "top_answer"),
        XCRG_Answer("CHEBI:2549", "Albuterol", "top_answer"),
        XCRG_Answer("CHEBI:8499", "Propranolol", "never_show", fails_on_arax = True),
    ]
)
def test_increased_activity_or_abundance_of_adrb2(response: Response, answer: XCRG_Answer):
    assert_answer(response, answer)
