# DO NOT MODIFY: This file was generated by scripts/generate_arax_tests
from dataclasses import replace

import pytest
from translator_tom import Response

import xcrg
from tests.utilities import (
    XCRG_Answer,
    assert_answer,
    find_chemicals_affecting_gene,
)

TEST_NAME = "arax_test_decreased_ddx3y"

@pytest.fixture(scope = "module")
def response(config: xcrg.XCRGConfig) -> Response:
    config = replace(config, debug_run_name = TEST_NAME)
    return find_chemicals_affecting_gene(config, "decreased", "NCBIGene:8653") # DDX3Y

@pytest.mark.xdist_group(name = TEST_NAME)
@pytest.mark.parametrize(
    "answer",
    [
        XCRG_Answer("UMLS:C0311474", "dna double stranded", "never_show"),
        XCRG_Answer("UMLS:C1328819", "Small molecule", "never_show"),
        XCRG_Answer("CHEBI:28748", "Doxorubicin", "acceptable", fails_on_arax = True),
        XCRG_Answer("UMLS:C4079590", "RK-33", "acceptable", fails_on_arax = True),
    ]
)
def test_decreased_activity_or_abundance_of_ddx3y(response: Response, answer: XCRG_Answer):
    assert_answer(response, answer)
