# DO NOT MODIFY: This file was generated by scripts/generate_arax_tests
from dataclasses import replace

import pytest
from translator_tom import Response

import xcrg
from tests.utilities import (
    XCRG_Answer,
    assert_answer,
    find_genes_affected_by_chemical,
)

TEST_NAME = "arax_test_increased_semaglutide"

@pytest.fixture(scope = "module")
def response(config: xcrg.XCRGConfig) -> Response:
    config = replace(config, debug_run_name = TEST_NAME)
    return find_genes_affected_by_chemical(config, "increased", "CHEBI:167574") # Semaglutide

@pytest.mark.xdist_group(name = TEST_NAME)
@pytest.mark.parametrize(
    "answer",
    [
        # NOTE: There are more tests for Semaglutide, but they do not currently return any results
        # TODO: This test appears to be erroneous or misconfigured
        XCRG_Answer("CHEBI:5931", "Insulin", "acceptable", fails_on_arax = True),
        XCRG_Answer("NCBIGene:2740", "GLP1R", "top_answer"),
    ]
)
def test_increased_activity_or_abundance_of_semaglutide(response: Response, answer: XCRG_Answer):
    assert_answer(response, answer)
