# DO NOT MODIFY: This file was generated by scripts/generate_arax_tests
from dataclasses import replace

import pytest
from translator_tom import Response

import xcrg
from tests.utilities import (
    XCRG_Answer,
    assert_answer,
    find_genes_affected_by_chemical,
)

TEST_NAME = "arax_test_increased_tamoxifen"

@pytest.fixture(scope = "module")
def response(config: xcrg.XCRGConfig) -> Response:
    config = replace(config, debug_run_name = TEST_NAME)
    return find_genes_affected_by_chemical(config, "increased", "CHEBI:41774") # Tamoxifen

@pytest.mark.xdist_group(name = TEST_NAME)
@pytest.mark.parametrize(
    "answer",
    [
        XCRG_Answer("NCBIGene:35292", "PR", "acceptable", fails_on_arax = True),
        XCRG_Answer("NCBIGene:817540", "pS2", "acceptable", fails_on_arax = True),
        XCRG_Answer("NCBIGene:1509", "CTSD", "acceptable"),
        XCRG_Answer("NCBIGene:817173", "ER", "acceptable", fails_on_arax = True),
        XCRG_Answer("NCBIGene:41957", "AKT", "acceptable", fails_on_arax = True),
        XCRG_Answer("UMLS:C2605860", "GPER-1", "acceptable"),
        XCRG_Answer("NCBIGene:1956", "EGFR", "acceptable"),
    ]
)
def test_increased_activity_or_abundance_of_tamoxifen(response: Response, answer: XCRG_Answer):
    assert_answer(response, answer)
