# DO NOT MODIFY: This file was generated by scripts/generate_arax_tests
from dataclasses import replace

import pytest
from translator_tom import Response

import xcrg
from tests.utilities import (
    XCRG_Answer,
    assert_answer,
    find_genes_affected_by_chemical,
)


@pytest.fixture(scope = "session")
def response(config: xcrg.XCRGConfig) -> Response:
    config = replace(config, debug_run_name = f"arax_test_62dcf4e6-d7a3-42ec-b1d9-e82bba048e90")
    return find_genes_affected_by_chemical(config, "increased", "CHEBI:41774") # Tamoxifen


@pytest.mark.parametrize(
    "answer",
    [
        XCRG_Answer("NCBIGene:35292", "acceptable", fails_on_arax = True), # PR
        XCRG_Answer("NCBIGene:817540", "acceptable", fails_on_arax = True), # pS2
        XCRG_Answer("NCBIGene:1509", "acceptable"), # CTSD
        XCRG_Answer("NCBIGene:817173", "acceptable", fails_on_arax = True), # ER
        XCRG_Answer("NCBIGene:41957", "acceptable", fails_on_arax = True), # AKT
        XCRG_Answer("UMLS:C2605860", "acceptable"), # GPER-1
        XCRG_Answer("NCBIGene:1956", "acceptable"), # EGFR
    ]
)
def test_increased_activity_or_abundance_of_tamoxifen(response: Response, answer: XCRG_Answer):
    assert_answer(response, answer)
