# DO NOT MODIFY: This file was generated by scripts/generate_arax_tests
from dataclasses import replace

import pytest
from translator_tom import Response

import xcrg
from tests.utilities import (
    XCRG_Answer,
    assert_answer,
    find_chemicals_affecting_gene,
)

TEST_NAME = "arax_test_decreased_hbb"

@pytest.fixture(scope = "module")
def response(config: xcrg.XCRGConfig) -> Response:
    config = replace(config, debug_run_name = TEST_NAME)
    return find_chemicals_affecting_gene(config, "decreased", "NCBIGene:3043") # HBB

@pytest.mark.xdist_group(name = TEST_NAME)
@pytest.mark.parametrize(
    "answer",
    [
        XCRG_Answer("CHEBI:50131", "decitabine", "top_answer", fails_on_arax = True),
        XCRG_Answer("PUBCHEM.COMPOUND:26945", "Hemin", "top_answer", fails_on_arax = True),
        XCRG_Answer("CHEBI:2038", "azacitidine", "top_answer", fails_on_arax = True),
        XCRG_Answer("UMLS:C0581820", "ButyrateDerivatives", "top_answer", fails_on_arax = True),
        XCRG_Answer("CHEBI:64103", "sodiumbutyrate", "top_answer", fails_on_arax = True),
        XCRG_Answer("UNII:IK8S1P79MU", "arginine butyrate", "top_answer", fails_on_arax = True),
        # BUG: https://github.com/NCATSTranslator/Tests/issues/80
        XCRG_Answer("CHEMBL:4034633", "DNMT inhibitor", "top_answer", fails_on_arax = True),
        XCRG_Answer("CHEBI:18050", "L-Glutamine", "acceptable", fails_on_arax = True),
        XCRG_Answer("CHEBI:44423", "Hydroxyurea", "acceptable"),
    ]
)
def test_decreased_activity_or_abundance_of_hbb(response: Response, answer: XCRG_Answer):
    assert_answer(response, answer)
