# DO NOT MODIFY: This file was generated by scripts/generate_arax_tests
from dataclasses import replace

import pytest
from translator_tom import Response

import xcrg
from tests.utilities import (
    XCRG_Answer,
    assert_answer,
    find_chemicals_affecting_gene,
)

TEST_NAME = "arax_test_decreased_brca2"

@pytest.fixture(scope = "module")
def response(config: xcrg.XCRGConfig) -> Response:
    config = replace(config, debug_run_name = TEST_NAME)
    return find_chemicals_affecting_gene(config, "decreased", "NCBIGene:675") # BRCA2

@pytest.mark.xdist_group(name = TEST_NAME)
@pytest.mark.parametrize(
    "answer",
    [
        XCRG_Answer("UNII:9X5A2QIA7C", "PARP inhibitor 2X-121", "acceptable", fails_on_arax = True),
        XCRG_Answer("CHEBI:16731", "Cinnamaldehyde", "bad_but_forgivable"),
        XCRG_Answer("CHEBI:16842", "Formaldehyde", "bad_but_forgivable", fails_on_arax = True),
        XCRG_Answer("PUBCHEM.COMPOUND:14423521", "Ursolic aldehyde", "bad_but_forgivable"),
        XCRG_Answer("CHEBI:31355", "Carboplatin", "acceptable", fails_on_arax = True),
        XCRG_Answer("CHEBI:176844", "niraparib", "acceptable"),
        XCRG_Answer("CHEBI:83766", "olaparib", "acceptable"),
        XCRG_Answer("CHEBI:62880", "veliparib", "acceptable"),
        XCRG_Answer("CHEBI:134689", "rucaparib", "acceptable", fails_on_arax = True),
        XCRG_Answer("CHEBI:231344", "talazoparib", "acceptable"),
        XCRG_Answer("CHEBI:27899", "Cisplatin", "acceptable"),
        XCRG_Answer("CHEBI:167900", "PJ34", "acceptable", fails_on_arax = True),
        XCRG_Answer("CHEBI:41774", "Tamoxifen", "acceptable"),
    ]
)
def test_decreased_activity_or_abundance_of_brca2(response: Response, answer: XCRG_Answer):
    assert_answer(response, answer)
