# DO NOT MODIFY: This file was generated by scripts/generate_arax_tests
from dataclasses import replace

import xcrg
from tests.utilities import (
    XCRG_Answer,
    assert_answer,
    find_chemicals_affecting_gene,
    find_genes_affected_by_chemical,
)


def test_ivacaftor_increased_activity_or_abundance_of_cftr(config: xcrg.XCRGConfig):
    config = replace(config, debug_run_name = f"arax_test_bd9cc2ef-d1e0-43cd-aa1b-a723bb15b26d")
    response = find_chemicals_affecting_gene(config, "increased", "NCBIGene:1080")  # CFTR
    assert_answer(response, XCRG_Answer("CHEBI:66901", "acceptable"))  # Ivacaftor


def test_adra2a_increased_activity_or_abundance_of_guafacine(config: xcrg.XCRGConfig):
    config = replace(config, debug_run_name = f"arax_test_9845b196-8e3c-42ad-b172-e984e7a3c665")
    response = find_genes_affected_by_chemical(config, "increased", "CHEBI:5558")  # Guafacine
    assert_answer(response, XCRG_Answer("NCBIGene:150", "acceptable"))  # ADRA2A


def test_bcl2_decreased_activity_or_abundance_of_docetaxel(config: xcrg.XCRGConfig):
    config = replace(config, debug_run_name = f"arax_test_ca6a81c8-9626-4e42-8e6c-3d9fe344f580")
    response = find_genes_affected_by_chemical(config, "decreased", "CHEBI:4672")  # Docetaxel
    assert_answer(response, XCRG_Answer("NCBIGene:596", "acceptable"))  # BCL2


def test_guafacine_increased_activity_or_abundance_of_dlg4(config: xcrg.XCRGConfig):
    config = replace(config, debug_run_name = f"arax_test_22812a8e-de59-471a-b13f-7cc18d0eb6fb")
    response = find_chemicals_affecting_gene(config, "increased", "NCBIGene:1742")  # DLG4
    assert_answer(response, XCRG_Answer("CHEBI:5558", "acceptable"))  # Guafacine


def test_ng_nitroarginine_methyl_ester_increased_activity_or_abundance_of_acetylcholine(config: xcrg.XCRGConfig):
    config = replace(config, debug_run_name = f"arax_test_076b3b1b-bc68-42e3-a5c0-38418ca222a5")
    response = find_genes_affected_by_chemical(config, "increased", "CHEBI:15355")  # Acetylcholine
    assert_answer(response, XCRG_Answer("UMLS:C0083536", "never_show"))  # NG-Nitroarginine Methyl Ester


def test_cancer_decreased_activity_or_abundance_of_myc(config: xcrg.XCRGConfig):
    config = replace(config, debug_run_name = f"arax_test_352c02bd-878a-47a2-9aec-822d05545b5d")
    response = find_genes_affected_by_chemical(config, "decreased", "NCBIGene:4609")  # MYC
    assert_answer(response, XCRG_Answer("MONDO:0004992", "never_show"))  # cancer


def test_ppara_increased_activity_or_abundance_of_clofibric_acid(config: xcrg.XCRGConfig):
    config = replace(config, debug_run_name = f"arax_test_10a839e0-2ed5-4e2b-a6d2-f2a385672e39")
    response = find_genes_affected_by_chemical(config, "increased", "CHEBI:34648")  # clofibric acid
    assert_answer(response, XCRG_Answer("NCBIGene:5465", "top_answer"))  # PPARA


def test_dabrafenib_decreased_activity_or_abundance_of_braf(config: xcrg.XCRGConfig):
    config = replace(config, debug_run_name = f"arax_test_4ff73493-c994-4d41-bc00-14234e2ab0bf")
    response = find_chemicals_affecting_gene(config, "decreased", "NCBIGene:673")  # BRAF
    assert_answer(response, XCRG_Answer("CHEBI:75045", "acceptable"))  # Dabrafenib


# TODO: This fails on ARAX because the output_id "NCBI:2629" is incorrect?
def test_gba1_decreased_activity_or_abundance_of_eliglustat(config: xcrg.XCRGConfig):
    config = replace(config, debug_run_name = f"arax_test_58c6bf8f-1713-470f-86b7-645e57b407ec")
    response = find_genes_affected_by_chemical(config, "decreased", "CHEBI:82752")  # Eliglustat
    assert_answer(response, XCRG_Answer("NCBIGene:2629", "acceptable", fails_on_arax = True))  # GBA1


def test_canagliflozin_decreased_activity_or_abundance_of_slc5a2(config: xcrg.XCRGConfig):
    config = replace(config, debug_run_name = f"arax_test_7d611ba7-9b6c-4dd2-8658-2931729016f0")
    response = find_chemicals_affecting_gene(config, "decreased", "NCBIGene:6524")  # SLC5A2
    assert_answer(response, XCRG_Answer("CHEBI:73274", "top_answer"))  # Canagliflozin


def test_naphthalene_decreased_activity_or_abundance_of_bpifa1(config: xcrg.XCRGConfig):
    config = replace(config, debug_run_name = f"arax_test_21e111fb-fd81-4a97-8275-f5dc77d47fa8")
    response = find_chemicals_affecting_gene(config, "decreased", "NCBIGene:51297")  # BPIFA1
    assert_answer(response, XCRG_Answer("CHEBI:16482", "acceptable"))  # Naphthalene


def test_acarbose_decreased_activity_or_abundance_of_mgam(config: xcrg.XCRGConfig):
    config = replace(config, debug_run_name = f"arax_test_ec342279-7951-4ccc-a65b-c6f1ce71062c")
    response = find_chemicals_affecting_gene(config, "decreased", "NCBIGene:8972")  # MGAM
    assert_answer(response, XCRG_Answer("CHEBI:2376", "top_answer", fails_on_arax = True))  # Acarbose


def test_warfarin_decreased_activity_or_abundance_of_vkorc1(config: xcrg.XCRGConfig):
    config = replace(config, debug_run_name = f"arax_test_2f1dc291-eaf5-46fc-bd8c-35f1f63ec810")
    response = find_chemicals_affecting_gene(config, "decreased", "NCBIGene:79001")  # VKORC1
    assert_answer(response, XCRG_Answer("CHEBI:10033", "top_answer"))  # Warfarin


def test_cyp3a4_decreased_activity_or_abundance_of_nirmatrelvir(config: xcrg.XCRGConfig):
    config = replace(config, debug_run_name = f"arax_test_dce4ebec-dfd0-4feb-93f8-bb19603ed8e3")
    response = find_genes_affected_by_chemical(config, "decreased", "CHEBI:170007")  # Nirmatrelvir
    assert_answer(response, XCRG_Answer("NCBIGene:1576", "acceptable", fails_on_arax = True))  # CYP3A4


def test_ppara_increased_activity_or_abundance_of_permethrin(config: xcrg.XCRGConfig):
    config = replace(config, debug_run_name = f"arax_test_69f3e42f-b86e-46ae-8a56-d7d8699975df")
    response = find_genes_affected_by_chemical(config, "increased", "CHEBI:34911")  # Permethrin
    assert_answer(response, XCRG_Answer("NCBIGene:5465", "top_answer", fails_on_arax = True))  # PPARA


def test_sildenafil_decreased_activity_or_abundance_of_pde5a(config: xcrg.XCRGConfig):
    config = replace(config, debug_run_name = f"arax_test_7fd2d98f-b4df-49e4-8fce-d9e6faca73ec")
    response = find_chemicals_affecting_gene(config, "decreased", "NCBIGene:8654")  # PDE5A
    assert_answer(response, XCRG_Answer("CHEBI:9139", "top_answer"))  # Sildenafil


def test_mrtx_1133_decreased_activity_or_abundance_of_kras(config: xcrg.XCRGConfig):
    config = replace(config, debug_run_name = f"arax_test_b1560d85-59dd-4d62-af2c-ed350fdb34db")
    response = find_chemicals_affecting_gene(config, "decreased", "NCBIGene:3845")  # KRAS
    assert_answer(response, XCRG_Answer("PUBCHEM.COMPOUND:156124857", "top_answer", fails_on_arax = True))  # MRTX-1133
