[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "catrax-xcrg"
version = "0.1.0"
description = "Reusable xCRG MVP2 TRAPI response generation."
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Translator CATRAX" }
]
dependencies = [
    "bmt>=1.4.6",
    "httpx~=0.28",
    "translator_tom==1.2.1",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
]

[dependency-groups]
dev = [
    "pyright==1.1.411",
    "pytest==9.1.1",
    "ruff==0.15.22",
    "ty==0.0.63"
]

[project.urls]
Homepage = "https://github.com/Translator-CATRAX/xCRG"
Issues = "https://github.com/Translator-CATRAX/xCRG/issues"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"xcrg.resources" = ["*.json"]

[tool.pytest.ini_options]
# Additional pytest configuration is performed in tests/conftest.py
pythonpath = ["src"]
testpaths = ["tests"]
# Only run unit tests by default.
# Comment this line if you want better support in IDE's like PyCharm, etc.
addopts = ["-m unit"]

[tool.ruff.lint]
ignore = [
    "E701" # multiple-statements-on-one-line-colon
]