#!/usr/bin/env python3
import json
import math
import sys
from math import ceil
from pathlib import Path
from typing import Callable

from optuna import Trial, create_study
from optuna.storages import JournalStorage
from optuna.storages.journal import JournalFileBackend
from translator_tom import CURIE

from xcrg.biolink import Agent_Type, Knowledge_Level
from xcrg.ranking import (
    Count_Category,
    Evidence_Category,
    QualifiedStatement, RRF_Ranker, Ranker, Result_Summary,
    Scoring_Params, Custom_Ranker
)


LOG_FUNCTIONS: dict[str, Callable[[float], float]] = {
    "identity": lambda x: x,
    "log": math.log,
    "log2": math.log2,
    "log10": math.log10
}

LOG_FUNCTION_STRS: dict[str, str] = {
    "identity": "lambda x: x",
    "log": "math.log",
    "log2": "math.log2",
    "log10": "math.log10"
}


def evaluate_test_expectation(answer_id: CURIE, answer_ids: list[CURIE], expectation: str) -> bool:
    match expectation:
        case "exists":             return answer_id in answer_ids
        case "top_answer":         return answer_id in answer_ids[0:max(30, ceil(len(answer_ids) / 10))]
        case "acceptable":         return answer_id in answer_ids[0:ceil(len(answer_ids) / 2)]
        case "bad_but_forgivable": return answer_id not in answer_ids[0:ceil(len(answer_ids) / 2)]
        case "never_show":         return answer_id not in answer_ids
        case _:                    raise ValueError(f"Invalid AnswerExpectation: {expectation}")


def make_objective(project_dir: Path):
    json_file = project_dir / "scripts/arax_tests.json"
    with open(json_file, "r") as f:
        arax_tests = json.load(f)

    test_id_to_summaries = dict[str, list[Result_Summary]]()
    for test in arax_tests:
        test_id: str = test["id"]
        test_safe_name = test["candidate_name"].replace(" ", "_").lower() # TODO
        test_dir = project_dir / f"output/debug/arax_test_{test["direction"]}_{test_safe_name}"

        matches = list(test_dir.glob("*.xcrg_scored_results.json"))
        json_file = matches[0]
        with open(json_file, "r") as f:
            xcrg_scored_results = json.load(f)

        for result in xcrg_scored_results:
            # Bunch of hacks to turn the json back into dataclasses
            result["result"] = None
            del result["rank"]
            summary = Result_Summary(**result)
            summary.direct_qualified_stmts = [
                QualifiedStatement(**x)
                for x in summary.direct_qualified_stmts
            ]
            summary.xcrg_qualified_stmts = [
                QualifiedStatement(**x)
                for x in summary.xcrg_qualified_stmts
            ]
            test_id_to_summaries.setdefault(test_id, []).append(summary)

    def objective(trial: Trial) -> int:
        params = Scoring_Params(
            k = trial.suggest_int(f"k", 0, 100),
            agent_type_weights = {
                x: trial.suggest_int(f"Agent_Type.{x.value}.weight", 1, 100)
                for x in Agent_Type
            },
            knowledge_level_weights = {
                x: trial.suggest_int(f"Knowledge_Level.{x.value}.weight", 1, 100)
                for x in Knowledge_Level
            },
            confidence_factor = trial.suggest_int("confidence_factor", 1, 100),
            category_weights = {
                x: Count_Category(
                    log_function = LOG_FUNCTIONS[
                        trial.suggest_categorical(
                            f"Evidence_Category.{x.value}.log_function",
                            ["identity", "log", "log2", "log10"],
                        )
                    ],
                    factor = trial.suggest_int(f"Evidence_Category.{x.value}.factor", 1, 100)
                )
                for x in Evidence_Category
            },
            direct_evidence_weight = trial.suggest_int("direct_evidence_weight", 1, 100),
            ngd_score_factor = trial.suggest_int("ngd_score_factor", 1, 1_000_000_000),
        )

        ranker: Ranker = Custom_Ranker(params)
        # ranker: Ranker = RRF_Ranker(params)

        passed_tests = 0
        for test in arax_tests:
            summaries = { x.curie: x for x in test_id_to_summaries[test["id"]] }
            summaries = ranker.rank_results(summaries)
            answer_ids = [x.curie for x in summaries]
            answer_ids = answer_ids[0:500] # TODO
            for answer in test["answers"]:
                answer_id = answer["id"]
                expectation = answer["expectation"]
                if evaluate_test_expectation(answer_id, answer_ids, expectation):
                    passed_tests += 1
        return passed_tests

    return objective


def main():
    script_file = Path(sys.argv[0])
    project_dir = script_file.parent.parent # TODO: fragile

    output_dir = project_dir / "output"
    output_dir.mkdir(exist_ok = True)

    study = create_study(
        direction = "maximize",
        storage = JournalStorage(JournalFileBackend(file_path = str(output_dir) + "/optuna_journal.log"))
    )
    objective = make_objective(project_dir)
    study.optimize(objective, n_trials = 1000, n_jobs = 4)

    print(study.best_value)
    print(study.best_params)

    results_file = output_dir / "optuna_results.py"

    s = "Scoring_Params(\n"
    s += f"     k = {study.best_params["k"]},\n"
    s +=  "     agent_type_weights = {\n"
    for x in Agent_Type:
        value = study.best_params[f"Agent_Type.{x.value}.weight"]
        s += f"        Agent_Type.{x.name}: {value},\n"
    s += "    },\n"
    s += "    knowledge_level_weights = {\n"
    for x in Knowledge_Level:
        value = study.best_params[f"Knowledge_Level.{x.value}.weight"]
        s += f"        Knowledge_Level.{x.name}: {value},\n"
    s += "    },\n"
    s += f"    confidence_factor = {study.best_params["confidence_factor"]},\n"
    s +=  "    category_weights = {\n"
    for x in Evidence_Category:
        log_function = study.best_params[f"Evidence_Category.{x.value}.log_function"]
        factor = study.best_params[f"Evidence_Category.{x.value}.factor"]
        s += f"        Evidence_Category.{x.name}: Count_Category(\n"
        s += f"            log_function = {LOG_FUNCTION_STRS[log_function]},\n"
        s += f"            factor = {factor}\n"
        s +=  "         ),\n"
    s += "    },\n"
    s += f"    direct_evidence_weight = {study.best_params["direct_evidence_weight"]},\n"
    s += f"    ngd_score_factor = {study.best_params["ngd_score_factor"]},\n"
    s += ")\n"

    with open(results_file, "w") as f:
        f.write(f"MOST_TESTS_PASSED = {study.best_value}\n")
        f.write(f"BEST_PARAMS = {s}")


if __name__ == "__main__":
    main()
